from __future__ import annotations

from typing import Protocol

from .models import AccountRequest, ChatMessage, DirectoryUser, EmailMessage, UnlockRequest, VerificationCode


class AccountRequestRepository(Protocol):
    def save(self, item: AccountRequest) -> None: ...
    def get(self, request_id: str) -> AccountRequest | None: ...
    def delete(self, request_id: str) -> None: ...
    def list_all(self) -> list[AccountRequest]: ...


class UnlockRequestRepository(Protocol):
    def save(self, item: UnlockRequest) -> None: ...
    def get(self, request_id: str) -> UnlockRequest | None: ...
    def delete(self, request_id: str) -> None: ...


class VerificationCodeRepository(Protocol):
    def save(self, item: VerificationCode) -> None: ...
    def get(self, username: str) -> VerificationCode | None: ...
    def delete(self, username: str) -> None: ...


class DirectoryPort(Protocol):
    def create_user(self, user: DirectoryUser, temporary_password: str) -> None: ...
    def reset_password(self, username: str, new_password: str) -> None: ...


class IdentityVerifierPort(Protocol):
    def verify_password(self, username: str, password: str) -> bool: ...


class NotificationPort(Protocol):
    def send(self, message: str) -> None: ...


class EmailPort(Protocol):
    def send(self, message: EmailMessage) -> None: ...


class AutomationPort(Protocol):
    def run_unlock(self, username: str, email: str) -> None: ...


class AIChatPort(Protocol):
    def reply(self, history: list[ChatMessage], system_prompt: str) -> str: ...
